---
go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'arm'
  armv6l: 'arm6vl'

go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"

victoriametrics_service_args:
  storageDataPath: "{{ victoriametrics_data_dir }}"
  selfScrapeInterval: "{{ victoriametrics_self_scrape_interval }}"
  retentionPeriod: "1d"
  maxConcurrentInserts: 32
  "search.maxUniqueTimeseries": "{{ victoriametrics_search_max_unique_timeseries }}"

